platform :ios, '9.0'
target '点吧' do
 pod 'Masonry'
 pod 'SDAutoLayout'
 pod 'SVProgressHUD'
 pod 'MJRefresh'
 pod 'SDWebImage'
 pod 'YYModel'
 pod 'FMDB'
 pod 'AFNetworking'
 pod 'SDCycleScrollView'
 pod'MJExtension'
 pod 'PYSearch'
end
